class map{
	constructor(){
		console.log("mapa: carregando..");

		this.blacktile = new Image();
		this.blacktile.src="../Images/blacktile.png";

		this.grass = new Image();
		this.grass.src = "../Images/grass.png";

		this.client = new Image();
		this.client.src = "../Images/cliente.png";

		this.road = new Image();
		this.road.src = "../Images/estrada.PNG";

		this.roadFinal = new Image();
		this.roadFinal.src = "../Images/roadFinal.png";

		this.lava = new Image();
		this.lava.src = "../Images/lava.png";

		this.house = new Image();
		this.house.src = "../Images/BrickHouse.png";

		this.shield = new Image();
		this.shield.src = "../Images/shield.png";

		this.ferroE = new Image();
		this.ferroE.src = "../Images/portaEsq.png";

		this.ferroD = new Image();
		this.ferroD.src = "../Images/portaDir.png";

		this.madE = new Image();
		this.madE.src = "../Images/porta2Esq.png";

		this.madD = new Image();
		this.madD.src = "../Images/porta2Dir.png";

		this.mapvector={};

		this.map1=[
			   [["grass","",1],["roadFinal","",1],["roadFinal","",1],["roadFinal","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["roadFinal","",0],["roadFinal","",0],["roadFinal","",0],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]]];

		this.map2=[
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","client",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["road","",0],["road","shield",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","shield",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","shield",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","madE",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","ferroE",1],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","shield",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","madD",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","madD",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","ferroD",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","ferroE",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","port",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","ferroE",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","ferroE",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","shield",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]],
			   [["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1],["grass","",1]]];

		this.map3=[
			   [["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1]],
			   [["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["road","",0],["lava","",1]],
			   [["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1]],
			   [["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1],["lava","",1]]];

		this.mapaprincipal = this.map2;
		//this.mapaprincipal = this.map2;
	}
}